import { useState } from "react";
import InputBox from "./components/InputBox";
import useCurrencyInfo from "./hooks/useCurrencyinfo";
import "./App.css";

function App() {
  const [amount, setAmount] = useState(0);
  const [from, setFrom] = useState("usd");
  const [to, setTo] = useState("inr");
  const [convertedAmount, setConvertedAmount] = useState(0);
  const [showName, setShowName] = useState(false);
  const [isConverting, setIsConverting] = useState(false);


  const { data: currencyInfo, loading } = useCurrencyInfo(from);
  const options = Object.keys(currencyInfo || {});

  const convert = async () => {
  setIsConverting(true); // start spinner

  if (!currencyInfo[to] || amount === 0) {
    setConvertedAmount(0);
    setShowName(false);
    setIsConverting(false);
    return;
  }

  await new Promise((res) => setTimeout(res, 600));

  setConvertedAmount(amount * currencyInfo[to]);
  setShowName(true);
  setIsConverting(false); 
};

  const swap = () => {
    setFrom(to);
    setTo(from);
    setConvertedAmount(amount);
    setAmount(convertedAmount);
  };

  return (
    <div
      className="w-full h-screen flex flex-wrap justify-center items-center bg-cover bg-no-repeat"
      style={{
        backgroundImage: `url('https://images.pexels.com/photos/730564/pexels-photo-730564.jpeg')`,
      }}
    >
      <div className="w-full">
        <div className="w-full max-w-md mx-auto border border-gray-60 rounded-lg p-5 backdrop-blur-sm bg-white/30">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              convert();
            }}
          >
         {(loading || isConverting) && (
  <div className="flex justify-center items-center mb-3">
    <div className="w-6 h-6 border-4 border-blue-500 border-t-transparent rounded-full animate-slow-spin"></div>
    <span className="ml-2 text-black-700 font-medium">
      {loading ? "Fetching rates..." : "Converting..."}
    </span>
  </div>
)}



            {/* FROM Input */}
            <div className="w-full mb-1">
              <InputBox
                label="From"
                amount={amount}
                currencyOptions={options}
                onCurrencyChange={(currency) => setFrom(currency)}
                selectCurrency={from}
                onAmountChange={(value) => setAmount(value)}
              />
            </div>

            {/* SWAP Button */}
            <div className="relative w-full h-0.5">
              <button
                type="button"
                className="absolute left-1/2 -translate-x-1/2 -translate-y-1/2 border-2 border-white rounded-md bg-blue-600 text-white px-2 py-0.5"
                onClick={swap}
              >
                Swap
              </button>
            </div>

            {/* TO Input */}
            <div className="w-full mt-1 mb-4">
              <InputBox
                label="To"
                amount={convertedAmount}
                amountDisabled={true}
                currencyOptions={options}
                onCurrencyChange={(currency) => setTo(currency)}
                selectCurrency={to}
              />
            </div>

            {/* CONVERT Button */}
            <button
              type="submit"
              className="w-full bg-blue-600 text-white px-4 py-3 rounded-lg"
            >
              Convert {from.toUpperCase()} to {to.toUpperCase()}
            </button>

            {/* YOUR NAME */}
            {showName && (
              <p className="text-center mt-3 text-xl font-semibold text-black-700">
                Generated by : Upendra Seervi
              </p>
            )}
          </form>
        </div>
      </div>
    </div>
  );
}

export default App;
